----FUNCTIONS


---FUNCTION 1

---CALCULATE THE TOTAL ROOM CHARGE FOR EACH PATIENT THAT WERE ASSIGNED A ROOM
	
CREATE OR REPLACE function TOTAL_ROOM_CHARGES(INVOICE_ID INTEGER)
	RETURNS INTEGER
	LANGUAGE PLPGSQL
	AS
	$$
	
	DECLARE
	    ROOM_CHARGE INTEGER;
	
	BEGIN
	
		 SELECT 
		 (ROOM_CHARGE_PER_DAY * NUMBER_OF_DAYS) as ROOM_CHARGE_TOTAL
		 INTO ROOM_CHARGE
		 FROM BILL
		 WHERE BILL.INVOICE_ID = TOTAL_ROOM_CHARGES.INVOICE_ID;
	

	     RETURN (ROOM_CHARGE);
	END;
	
	$$;
	
	
	--TESTING FUNCTION
	
         SELECT TOTAL_ROOM_CHARGES(1) ;
         SELECT TOTAL_ROOM_CHARGES(10) ;
         SELECT TOTAL_ROOM_CHARGES(13) ;







---fUNCTION 2

---CALCULATE THE TOTAL HOSPITAL BILLS FOR EACH PATIENTS 
	
CREATE OR REPLACE function TOTAL_BILL (INVOICE_ID INTEGER)
	returnS INTEGER
	language PLPGSQL
	AS
	$$
	
	declare 
	    OUTSTANDING_BALANCE INTEGER;
	
	BEGIN
	
		 SELECT
		 (DOCTOR_CHARGES + TEST_CHARGE + PRESCRIPTION_CHARGES +  (ROOM_CHARGE_PER_DAY * NUMBER_OF_DAYS))
		 INTO OUTSTANDING_BALANCE
		 FROM bill
		 WHERE BILL.INVOICE_ID = TOTAL_BILL.INVOICE_ID;
	

	     RETURN (OUTSTANDING_BALANCE);
	END;
	
	$$;
	
	
	--TESTING FUNCTION
	
         SELECT TOTAL_BILL(1) ;
		 SELECT TOTAL_BILL(5) ;
         SELECT TOTAL_BILL(10) ;
         SELECT TOTAL_BILL(15) ;
		 




		 		 
---------fUNCTION 3

---CALCULATE THE TOTAL HOSPITAL BILLS FOR EACH PATIENTS (eXTENSIVE)	 
		 
		  CREATE OR REPLACE FUNCTION TOTAL_OUTSTANDING_BILLS(INVOICE_ID integer)
		  RETURNS table ( PATIENT_ID INTEGER,
						 PATIENT_NAME TEXT,
						 TOTAL_BILL numeric(8,2))

		  LANGUAGE plpgsql
		  AS 
		  $$

		  BEGIN

		  RETURN QUERY
				 SELECT
				 B.PATIENT_ID,
				 TRIM(CONCAT(A.FIRST_NAME,' ', A.LAST_NAME))as PATIENT_NAME,
				 (DOCTOR_CHARGES + TEST_CHARGE + PRESCRIPTION_CHARGES +  (ROOM_CHARGE_PER_DAY * NUMBER_OF_DAYS)) as TOTAL_BILL
				 FROM BILL B
				 INNER JOIN PATIENT A USING (PATIENT_ID)
				 WHERE B.INVOICE_ID = TOTAL_OUTSTANDING_BILLS.INVOICE_ID;
			END;

			$$;


--TESTING FUNCTION

SELECT TOTAL_OUTSTANDING_BILLS(3)
SELECT TOTAL_OUTSTANDING_BILLS(6)
SELECT TOTAL_OUTSTANDING_BILLS(9)
SELECT TOTAL_OUTSTANDING_BILLS(12)
SELECT TOTAL_OUTSTANDING_BILLS(15)		 
		 
		 
		 
		 
		 
		 
		 
		 
		
		 SELECT TOTAL_BILL(20) ;