----Views


-----view 1

CREATE OR REPLACE VIEW Female_patients_doctors
AS
SELECT
CONCAT(D.FIRST_NAME,' ', D.LAST_NAME)as DOCTOR_NAME,
D.GENDER AS DOCTOR_GENDER,
CONCAT(P.FIRST_NAME,' ', P.LAST_NAME)as PATIENT_NAME,
D.EMAIL AS DOCTORS_EMAIL ,
P.EMAIL AS PATIENTS_EMAIL,
P.ADDRESS AS PATIENT_ADDRESS,
EXTRACT (YEAR FROM CURRENT_DATE) - P.AGE AS PATIENTS_YEAR_OF_BIRTH
FROM DOCTOR D
INNER JOIN PATIENT P ON D.DOCTOR_ID=P.DOCTOR_ID
WHERE P.GENDER='Female';

select * from Female_patients_doctors
ORDER BY PATIENTS_YEAR_OF_BIRTH



-----view 2

CREATE OR REPLACE VIEW Male_patients_doctors
AS
SELECT
CONCAT(D.FIRST_NAME,' ', D.LAST_NAME)as DOCTOR_NAME,
D.GENDER AS DOCTOR_GENDER,
CONCAT(P.FIRST_NAME,' ', P.LAST_NAME)as PATIENT_NAME,
D.EMAIL AS DOCTORS_EMAIL ,
P.EMAIL AS PATIENTS_EMAIL,
P.ADDRESS AS PATIENT_ADDRESS,
EXTRACT (YEAR FROM CURRENT_DATE) - P.AGE AS PATIENTS_YEAR_OF_BIRTH
FROM DOCTOR D
INNER JOIN PATIENT P ON D.DOCTOR_ID=P.DOCTOR_ID
AND P.GENDER='Male';

select * from Male_patients_doctors














